variable "region" { }
variable "profile" { }
variable "number_of_slave" { }
variable "name_master" { } 
variable "name_slave" { } 
variable "createdby" { } 
variable "ami" { }
variable "instance_type" { }
variable "vpc" { }
variable "RedShiftDev02" { }
variable "key_name" { }
