kind: Service
apiVersion: v1
metadata:
  name: phunginx
spec:
  selector:
    #app: phunginx 
    newapp: newapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#  externalIPs:
#  - 192.168.195.101
  #type: LoadBalancer

#selector:app:phunginx will point to the pod's label (not deployment/rs/statefulset)