apiVersion: v1
kind: Service
metadata:
  labels:
    app: mainsite
  name: mainsite
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mainsite
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
