apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-a
  name: service-a
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: service-a
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
