version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    volumes:
#      - /Users/ball/repo/jenkins/jenkins-master/log:/var/log/jenkins
#      - /Users/ball/repo/jenkins/jenkins-master/jenkins_home:/var/jenkins_home
      - /opt/jenkins/jenkins-master/jenkins_home:/var/log/jenkins
      - /opt/jenkins/jenkins-master/log:/var/jenkins_home

  nginx:
    image: nginx:1.17.10
    ports:
      - "8443:8443"
    volumes:
      - /opt/jenkins/jenkins-nginx/nginx:/etc/nginx
