version: "3.0"
services:
  puppetmaster:
    build:
      context: ./
      dockerfile: puppetmaster
    networks:
      app_net:
        ipv4_address: 172.16.1.90
  puppetagent:
    build:
      context: ./
      dockerfile: puppetagent
    networks:
      app_net:
        ipv4_address: 172.16.1.91
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24


